### ISSUE TITLE
Can you please explain how to test it on new videos...

### ISSUE THREAD

**Issue by leo19910821** [swathikirans/violence-recognition-pytorch#1]
Can you please explain how to test it on new videos...

**Comment by asadmujtaba** [comment]
I need to test it on some other videos can you please explain how i can do that

**Comment by swathikirans** [comment]
Hi, you can place the frames of your video inside a directory as shown in the figure in the description. The dataloader provided will read frames present in the directory sequentially.

**Comment by leo19910821** [comment]
Thanks for your quick reply... Is it possible to run it on live video feed???

**Comment by swathikirans** [comment]
The models gives a prediction only after analysing 20 frames. So there will be a small delay. If it is not a problem, you can modify the input pipeline in order to accept 20 frames continuously, from a live video feed.

**Comment by leo19910821** [comment]
Thanks for answer, appreciate it

**Comment by jaiminkansara** [comment]
@asadmujtaba were you able to work with live videos?
