### ISSUE TITLE
Cannot "from tensorboardX import SummaryWriter"

### ISSUE THREAD

**Issue by TinhinaneMEZAIR** [swathikirans/violence-recognition-pytorch#15]
Hello,
This line of code in main-run-vr.py :
from tensorboardX import SummaryWriter
Is not working, I tried to pip install tensorboard, other versions of tensorflow...and it is still not running
Could you please help me to fix it
Kind regards

**Comment by swathikirans** [comment]
Install tensorboardx as follows: pip install 'git+https://github.com/lanpa/tensorboardX'

**Comment by TinhinaneMEZAIR** [comment]
This gives me this error:
![image](https://user-images.githubusercontent.com/76223314/132844361-4fc7fd56-636b-4947-a2ae-d2fb4cff2ed9.png)
