### ISSUE TITLE
running code

### ISSUE THREAD

**Issue by Heyam91** [swathikirans/violence-recognition-pytorch#4]
How to pass parameters in command line?

**Comment by swathikirans** [comment]
python main-run-vr.py --numEpochs 100 \
--lr 1e-4 \
--stepSize 25 \
--decayRate 0.5 \
--seqLen 20 \
--trainBatchSize 16 \
--memSize 256 \
--evalInterval 5 \
--evalMode horFlip \
--numWorkers 4 \
--outDir violence \
--fightsDirTrain fightSamplesTrainDir \
--noFightsDirTrain noFightSamplesTrainDir \
--fightsDirTest fightSamplesTestDir \
--noFightsDirTest noFightSamplesTestDir

**Comment by Heyam91** [comment]
![cmd](https://user-images.githubusercontent.com/33684097/50762318-a5992580-127d-11e9-89ac-70966518b6c8.png)

I get this error!! how can i solve it? 
thank you

**Comment by Heyam91** [comment]
I get this error!! how can i solve it??

![cmd](https://user-images.githubusercontent.com/33684097/50762619-8bac1280-127e-11e9-8acf-79a618fd4c2a.png)

**Comment by swathikirans** [comment]
Use this command:

`python main-run-vr.py --numEpochs 100 \
--lr 1e-4 \
--stepSize 25 \
--decayRate 0.5 \
--seqLen 20 \
--trainBatchSize 16 \
--memSize 256 \
--evalInterval 5 \
--evalMode horFlip \
--numWorkers 4 \
--outDir violence \
--fightsDirTrain fightSamplesTrainDir \
--noFightsDirTrain noFightSamplesTrainDir \
--fightsDirTest fightSamplesTestDir \
--noFightsDirTest noFightSamplesTestDir`

**Comment by swathikirans** [comment]
Please see the readme file for the command.
