### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by Heyam91** [swathikirans/violence-recognition-pytorch#5]
parser.add_argument('--fightsDirTrain', type=str, default='./datasets/violent_flow/frames/fights', help='Directory containing training fight sequences')
parser.add_argument('--noFightsDirTrain', type=str, default='./datasets/violent_flow/frames/noFights', help='Directory containing training non-fight sequences')
parser.add_argument('--fightsDirTest', type=str, default='./datasets/violent_flow/frames/fights', help='Directory containing testing fight sequences')
parser.add_argument('--noFightsDirTest', type=str, default='./datasets/violent_flow/frames/noFights', 

Hi, 
in above lines, there are two folders in dataset fights/noFights . how can we separate the training and testing videos in same folder?
thank you ,,

**Comment by swathikirans** [comment]
You can modify the function "make_split" and then change lines 41 and 42 accordingly.
