### ISSUE TITLE
why is the accuracy almost 0?

### ISSUE THREAD

**Issue by huangshayue** [swathikirans/violence-recognition-pytorch#6]
Testing: Loss = 0.21947783728440604 | Accuracy = 0%
Epoch = 6
Training: Loss = 0.1409450491327186 | Accuracy = 0%
Epoch = 7
Training: Loss = 0.16877971823478854 | Accuracy = 0%
Epoch = 8
Training: Loss = 0.16165185234574383 | Accuracy = 0%
Epoch = 9
Training: Loss = 0.13852607493483743 | Accuracy = 0%
Epoch = 10
Training: Loss = 0.14300934883744218 | Accuracy = 0%
Evaluating...
Testing: Loss = 0.2319346371293068 | Accuracy = 0%
Epoch = 11
Training: Loss = 0.15146097653480464 | Accuracy = 0%
Epoch = 12
Training: Loss = 0.11182227800058764 | Accuracy = 0%
Epoch = 13
Training: Loss = 0.12626616214943487 | Accuracy = 0%
Epoch = 14

**Comment by Heyam91** [comment]
add .float() to following lines
trainAccuracy = (numCorrTrain.float() / numTrainInstances) * 100
testAccuracy = (numCorrTest.float() / numTestInstances) * 100

**Comment by swathikirans** [comment]
Thank you @Heyam91  for pointing this out. However, the code is based on python3. You have to add .float() only if it is python2.7
